### PR TITLE
post contribution

### PR DESCRIPTION
**Pull request by jessitron**
Tiffany,
I realized the other day that while I love being female, it does affect people's initial expectations. This works fine for me because I love to shock people - but for most people it hurts. That same day, you launched your site.

If you like it, please include this post. Feel free to change anything about it.

### CODE REVIEW

**Comment by theophani** [comment]
Hey Jessica,

Your post says a lot of things I also have thought and felt. It's also very in line with the sentiment “we are all awesome”.

Here's the challenge I'm facing: I want this site to be a cohesive resource for encouraging and helping women become conference speakers through self-selecting and self-promoting (i.e. deciding to volunteer). Your post, while important and related to the theme of encouragement, is tangential.

I'm uncertain how to include posts like this in the context of the rest of the site. A regular blog, with guest posts such as this one, could be quite a vibrant addition. The current setup of the site don't allow for categorization of posts, nor does it distinguish (like say Wordpress) between posts and pages.

Before I publish this on the site, I need to think a bit more about how to stucture content. It may take some time (a week or more) before I figure that out and make the structural changes.

Thanks for sharing this :). Let me know if I haven't explained myself, or you have any suggestions.
- Tiffany

**Comment by jessitron** [comment]
I can make it more focused on conference speaking, if you like.
I deliberately didn't because the basic point is relevant to more than that.

If you prefer, I can post it on my blog and you can tweet it :-)

Thanks for your feedback!
and you're right, keeping a tight focus for the site is important.

Your site is brilliant, btw.

On Wed, Jun 27, 2012 at 4:27 PM, Tiffany Conroy
reply@reply.github.com
wrote:

> Hey Jessica,
> 
> Your post says a lot of things I also have thought and felt. It's also very in line with the sentiment “we are all awesome”.
> 
> Here's the challenge I'm facing: I want this site to be a cohesive resource for encouraging and helping women become conference speakers through self-selecting and self-promoting (i.e. deciding to volunteer). Your post, while important and related to the theme of encouragement, is tangential.
> 
> I'm uncertain how to include posts like this in the context of the rest of the site. A regular blog, with guest posts such as this one, could be quite a vibrant addition. The current setup of the site don't allow for categorization of posts, nor does it distinguish (like say Wordpress) between posts and pages.
> 
> Before I publish this on the site, I need to think a bit more about how to stucture content. It may take some time (a week or more) before I figure that out and make the structural changes.
> 
> Thanks for sharing this :). Let me know if I haven't explained myself, or you have any suggestions.
> - Tiffany
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/janl/waaa/pull/19#issuecomment-6615950

## 

Jessica Kerr
jessitron@gmail.com
314.714.5237

**Comment by theophani** [comment]
I agree that the point you are making is relevant to much more than just conference speaking, and changing the post to shoe-horn it into a narrow application would not do it justice.

I'd be happy to tweet about the post if you put it on your own blog.

I'll still consider how I could add a section for tangential contributions such as this one.

Also, thanks :) _blush_

**Comment by jessitron** [comment]
great! http://blog.jessitron.com/2012/06/expect-to-fly.html

On Wed, Jun 27, 2012 at 4:42 PM, Tiffany Conroy
reply@reply.github.com
wrote:

> I agree that the point you are making is relevant to much more than just conference speaking, and changing the post to shoe-horn it into a narrow application would not do it justice.
> 
> I'd be happy to tweet about the post if you put it on your own blog.
> 
> I'll still consider how I could add a section for tangential contributions such as this one.
> 
> Also, thanks :) _blush_
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/janl/waaa/pull/19#issuecomment-6616339

## 

Jessica Kerr
jessitron@gmail.com
314.714.5237

**Comment by theophani** [comment]
I'm going to close this issue, but still think about how to include tangential guest posts.

**Pull request closed without merging**
